apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: default
  labels:
    app: backend-app
spec:
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      serviceAccountName: ghcr-sa
      containers:
        - name: backend-projects
          image: ghcr.io/agpriyanshu/backend-projects:latest
          imagePullPolicy: Always

          resources:
            requests:
              cpu: 4000m
              memory: 4000Mi
            limits:
              cpu: 4000m
              memory: 8000Mi

          ports:
            - containerPort: 8000
              name: backend-app

          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "postgres"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: DEBUG
              value: "1"
            # SeaweedFS S3 Configuration
            - name: S3_ENDPOINT
              value: "http://seaweedfs-s3:8333"
            - name: S3_REGION
              value: "ap-south-1"
            - name: S3_BUCKET
              value: "woa"
            - name: S3_ACCESS_KEY
              value: "EEQb7fnFvvDsoHdr3qZh"
            - name: S3_SECRET_KEY
              value: "PpuxU5kwQkt6mkqrde3k"