[tool.isort]
profile = "black"
skip_glob = ["k8s/*"]

[tool.ruff]
line-length = 88
lint.ignore = ["F841"]
exclude = ["*.yaml"]
fix = true

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401","F403"]
