apiVersion: v2
name: platform-namespaces
description: Namespaces and ReferenceGrants for platform components
type: application
version: 0.1.0
appVersion: "v1"
maintainers:
  - name: AgPriyanshu
    email: priyanshu81212@gmail.com
