apiVersion: v1
kind: Secret
metadata:
  name: { { include "minio.fullname" . } }
  labels: { { - include "minio.labels" . | nindent 4 } }
type: Opaque
data:
  rootUser: { { .Values.rootUser | b64enc | quote } }
  rootPassword: { { .Values.rootPassword | b64enc | quote } }
