apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend-route
spec:
  parentRefs:
    - name: platform-gateway
      namespace: gateway-ns
      sectionName: http
  hostnames:
    - "worldofapps.bar"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: frontend-app-service
          port: 80
          namespace: default
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-route
spec:
  parentRefs:
    - name: platform-gateway
      namespace: gateway-ns
      sectionName: http
  hostnames:
    - "api.worldofapps.bar"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: backend-service
          port: 80
          namespace: default
