apiVersion: v2
name: platform-registry
description: Docker images registry config
type: application
version: 0.1.0
appVersion: "v1"
maintainers:
  - name: AgPriyanshu
    email: priyanshu81212@gmail.com
