apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: gateway-system
data:
  config.yaml: |
    tunnel: {{ .Values.tunnel.name }}
    credentials-file: /etc/cloudflared/creds/credentials.json

    ingress:
      - hostname: {{ .Values.ingress.hostname }}
        service: {{ .Values.ingress.service }}
      - service: http_status:404
