apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    tunnel: {{ .Values.tunnel.name }}
    credentials-file: /etc/cloudflared/creds/credentials.json

    ingress:
{{- range .Values.ingress }}
      - hostname: {{ .hostname }}
        service: {{ .service }}
{{- end }}
      - service: http_status:404
