replicaCount: 1

image:
  repository: cloudflare/cloudflared
  tag: latest
  pullPolicy: IfNotPresent

tunnel:
  name: worldofapps
  credentialsJson: |
    {
      "AccountTag": "62042f9fcd5411eb85dc581b38dce3f2",
      "TunnelID": "458691f4-9827-4ee2-b0df-4ea2deea4a0c",
      "TunnelName": "worldofapps",
      "TunnelSecret": "eFIcCO80HYOslkijfdkWllqBDRaL+31htz3u9bEk4U4="
    }

ingress:
  - hostname: worldofapps.bar
    service: http://platform-gateway-nginx.gateway-ns.svc.cluster.local
  - hostname: api.worldofapps.bar
    service: http://platform-gateway-nginx.gateway-ns.svc.cluster.local

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
