apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}"
    .Values.docker.server
    .Values.docker.username
    .Values.docker.password
    .Values.docker.email
    (printf "%s:%s" .Values.docker.username .Values.docker.password | b64enc)
    | b64enc }}
